api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 24
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            items_per_page_parameter_name: 'count'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'

